name: Quality

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-checks:
    name: Static checks
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run checks
        run: |
          turbo run check-formatting lint typecheck
          pnpm check-monorepo

  quality-checks:
    name: Quality checks
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 22]
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}

      - name: Run tests
        run: |
          turbo run test

      - name: Try building
        run: turbo run build

      - name: Run E2E on a real project
        run: node ./packages/steiger/dist/cli.mjs ./examples/kitchen-sink-of-fsd-issues/src/ --reporter json > output.json
        continue-on-error: true

      - name: Compare output
        run: diff <(jq --sort-keys . output.json) <(jq --sort-keys . examples/kitchen-sink-of-fsd-issues/reference-output-${{ matrix.os }}.json)
